apiVersion: v1
kind: Service
metadata:
  name: webapp-lb
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: ekswebapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000